title: 徐曳恺 XU Yekai
subtitle: 追寻梦想，永不言弃！ Pursue my dreams and never give up!
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://jaimelavie.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: 首页 Home
      url: /
    - text: 项目 Projects
      url: /blog
    - text: 联系我 Contact Me
      url : /contact/#/
    # - text: Styleguide
    #   url: /styleguide/
    

# Edit these details 

author_logo: profile.jpg
author: XU Yekai
author_bio_zh: 我是清华伯克利深圳学院数据科学和信息技术专业硕士二年级学生徐曳恺，研究兴趣是：一、互联网研究+政治传播学，特别是与政治/国际关系相关的社交媒体数据分析；二、新兴技术与国际安全，特别是网络空间的（国际）治理和政策问题。
author_bio_en: 'Hi, I am XU Yekai, a master student at Tsinghua-Berkeley Shenzhen Institute (TBSI), Tsinghua University. My research interests include: 1) Internet studies & political communication on the internet, especially social media data analysis for politics & international relations studies; 2) emerging technologies and international security, especially the (international) governance of cyberspace.'
author_email: "xyk18@mails.tsinghua.edu.cn"
author_location: 中国北京、深圳 Beijing and Shenzhen, China
author_website_url: "https://jaimelavie.github.io/"
author_cv_zh_url: /assets/CV_Xu_Yekai_中文.pdf
author_cv_en_url: /assets/CV_Xu_Yekai.pdf

author_work_experiences:
            - company_name_zh: <a href="https://www.aiib.org/en/index.html">亚洲基础设施投资银行</a>
              company_name_en: <a href="https://www.aiib.org/en/index.html">Asian Infrastructure Investment Bank</a>
              company_logo: aiib.jpg
              # company_url: https://www.aiib.org/en/index.html
              designation_zh: 项目管理与文本分析实习生
              designation_en: Portfolio Management Analyst Consultant
              description_zh: 利用主题模型和关键词提取技术，总结在先前的投资行为中积累的知识；应用文本分析算法，使用世行、亚开行的开放数据，合并亚投行的数据以建立投资操作知识数据库（2020年12月-）
              description_en: Utilizing topic models and key word extraction techniques to provide insights into the knowledge accumulated during previous investment operations; Applying text analysis algorithms to help establish an operational database. (Dec. 2020 - )
              visibility: true
            - company_name_zh: <a href="https://www.unescap.org/">联合国亚洲及太平洋经济社会委员会</a>
              company_name_en: <a href="https://www.unescap.org/">United Nations ESCAP</a>
              company_logo: escap.png
              # company_url: https://www.unescap.org/
              designation_zh: 经济事务（科技政策）实习生
              designation_en: Economic Affairs Intern
              description_zh: 撰写关于医疗行业中的包容性企业的政策简报；组织<a href="https://artnet.unescap.org/sti/events/webinar-promoting-grassroots-innovation-present-situation-challenges-and-policies">推动草根创新在线研讨会</a>等（2020年5-11月）
              description_en: Completing a policy brief on inclusive businesses in the health sector; Organizing the <a href="https://artnet.unescap.org/sti/events/webinar-promoting-grassroots-innovation-present-situation-challenges-and-policies">Webinar on Promoting Grassroots Innovation</a>, etc. (May 2020 - Nov. 2020)
              visibility: true
            - company_name_zh: <a href="https://www.oppo.com/cn/">OPPO广东移动通信有限公司</a>
              company_name_en: <a href="https://www.oppo.com/en/">OPPO</a>
              company_logo: oppo.png
              # company_url: https://www.oppo.com/en/
              designation_zh: 安卓开发实习生
              designation_en: Android Development Intern
              description_zh: 调试CuttleFish模拟器（2019年5-6月）
              description_en: Worked on CuttleFish simulator (May 2019 - Jun. 2019)
              visibility: true
            - company_name_zh: <a href="https://www.yuntongxun.com/">容联易通信息技术有限公司</a>
              company_name_en: <a href="https://www.cloopen.com/">Cloopen</a>
              company_logo: cloopen.png
              # company_url: https://www.cloopen.com/
              designation_zh: 技术预研部实习生
              designation_en: Algorithm Intern
              description_zh: 人脸检测、活体检测（2018年6-8月）
              description_en: Worked on human face liveness detection and gesture recognition (Jun. 2018 - Aug. 2018)
              visibility: true

author_education_details:
              - college_logo: thu.png # tbsi.png
                college_name_zh: <a href="https://www.tsinghua.edu.cn/">清华大学</a>, <a href="https://www.tbsi.edu.cn/"> 清华-伯克利深圳学院</a>
                college_name_en: <a href="https://www.tbsi.edu.cn/en/">Tsinghua-Berkeley Shenzhen Institute</a>, <a href="https://www.tsinghua.edu.cn/publish/thu2018en/index.html"> Tsinghua University </a>
                # college_url: https://www.tbsi.edu.cn/en/
                college_degree_zh: 数据科学和信息技术
                college_degree_en: Data Science and Information Technology
                description_zh: 工学硕士，2018-2021（预期）
                description_en: Master of Science, 2018-2021 (Expected)
                visibility: true
              - college_logo: ecn.png
                college_name_zh: <a href="https://www.ec-nantes.fr/">法国南特中央理工学院</a>
                college_name_en: <a href="https://www.ec-nantes.fr/">École Centrale de Nantes, France</a>
                # college_url: https://www.ec-nantes.fr/
                college_degree_zh: 信号、控制与机器人
                college_degree_en: Signal, Control, and Robotics
                description_zh: 基础硕士（交换生），2017-2018
                description_en: Foundation Master (Exchange Student), 2017-2018
                visibility: true
              - college_logo: tju.png
                college_name_zh: <a href="http://www.tju.edu.cn/">天津大学</a>, <a href="http://seea.tju.edu.cn/"> 电气自动化与信息工程学院 </a>
                college_name_en: <a href="http://seea.tju.edu.cn/english/">School of Electrical and Information Engineering</a>, <a href="http://www.tju.edu.cn/english/"> Tianjin University </a>
                # college_url: http://www.tju.edu.cn/english/
                college_degree_zh: 自动化
                college_degree_en: Automation (Electrical and Electronic Engineering)
                description_zh: 工学学士，2014-2018
                description_en: Bachelor of Engineering, 2014-2018
                visibility: true

author_certificate_details:
              - certificate_logo: public_policy.jpg
                # college_url: https://www.coursera.org/account/accomplishments/certificate/A49272V49X9T
                certificate_name: Public Policy Challenges of the 21st Century
                institute_name_zh: Coursera网络课程，完成于2020年5月，参见<a href="https://www.coursera.org/account/accomplishments/verify/ED4C9MJGW4CT"> 证书 </a>
                institute_name_en: Coursera Online Course, May 2020, see <a href="https://www.coursera.org/account/accomplishments/verify/ED4C9MJGW4CT"> Certificate </a>
                visibility: true
              - certificate_logo: political_economy.jpg
                # college_url: https://www.coursera.org/account/accomplishments/certificate/A49272V49X9T
                certificate_name: Political Economy of Institutions and Development
                institute_name_zh: Coursera网络课程，完成于2019年12月，参见<a href="https://www.coursera.org/account/accomplishments/verify/H5Z8HJYM3BCZ"> 证书 </a>
                institute_name_en: Coursera Online Course, Dec 2019, see <a href="https://www.coursera.org/account/accomplishments/verify/H5Z8HJYM3BCZ"> Certificate </a>
                visibility: true
              - certificate_logo: international_relations.jpg
                # college_url: https://www.coursera.org/account/accomplishments/certificate/A49272V49X9T
                certificate_name: Understanding International Relations Theory
                institute_name_zh: Coursera网络课程，完成于2019年6月，参见<a href="https://www.coursera.org/account/accomplishments/verify/A49272V49X9T">证书</a>
                institute_name_en: Coursera Online Course, Jun 2019, see <a href="https://www.coursera.org/account/accomplishments/verify/A49272V49X9T"> Certificate </a> 
                visibility: true

author_project_details:
              - project_thumbnail: wcloud.png
                project_title: Evaluating Online Public Sentiments towards China：A Case Study of Twitter Discourse during the 2019 Chinese National Day
                project_description: <b>（仅英文）</b>收集并分析2019年10月1日前后与中国国庆有关的中英文推特数据，研究推特话语对华情感在时间、空间、用词等方面的特点。
                project_url: <a href="/social%20media%20&%20politics/2019/11/28/What-can-we-find-from-the-Chinese-National-Day-Twitter-data/"> 更多 Detail </a> | <a href="https://github.com/JaimeLaVie/National_Day_Public_Opinion_Mining"> Github </a> | <a href="https://ieeexplore.ieee.org/document/9334093"> 论文 Paper </a>
                visibility: true

author_contact_information:
              - contact_image: contact_me.jpg
                email: 电子邮件 E-mail： xyk18@mails.tsinghua.edu.cn
                tel: 电话 Tel： (+86) 15620079650
                visibility: true

# social links
twitter_username: XYekai
github_username:  JaimeLaVie
# facebook_username: 
linkedin_username: yekai-xu-b73596156/
# behance_username: 
# instagram_username: 
# medium_username: 
# telegram_username: 
# dribbble_username: 
# flickr_username: 

#for comments using disqus
# disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
wakatime_username: XU_Yekai

# formspree (contact form)
formspree_email: xyk18@mails.tsinghua.edu.cn

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_certificate_details: true
show_author_project_details: true
show_author_contact_information: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
