title: 徐曳恺 XU Yekai
subtitle: 追寻梦想，永不言弃！ Pursue my dreams and never give up!
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://jaimelavie.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: 首页 Home
      url: /
    - text: 项目 Projects
      url: /blog
    # - text: Shop
    #   url : /shop/
    - text: 联系我 Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide/
    

# Edit these details 

author_logo: profile.jpg
author: XU Yekai
author_bio_zh: 我是清华伯克利深圳学院数据科学和信息技术专业硕士二年级学生徐曳恺，研究方向是社会数据科学。
author_bio_en: Hi, I am XU Yekai, a master student at Tsinghua-Berkeley Shenzhen Institute (TBSI), Tsinghua University. My research interests are social data science.  
author_email: "xyk18@mails.tsinghua.edu.cn"
author_location: 中国北京、深圳 Beijing and Shenzhen, China
author_website_url: "https://jaimelavie.github.io/"

author_work_experiences: 
            - company_name_zh: <a href="https://www.oppo.com/cn/">OPPO广东移动通信有限公司</a>
              company_name_en: <a href="https://www.oppo.com/en/">OPPO</a>
              company_logo: oppo.png
              # company_url: https://www.oppo.com/en/
              designation: 安卓开发实习生 Android Development Intern
              description_zh: 调试CuttleFish模拟器（2019年5-6月）
              description_en: Worked on CuttleFish simulator (May 2019 - Jun 2019)
              visibility: true
            - company_name_zh: <a href="https://www.yuntongxun.com/">容联易通信息技术有限公司</a>
              company_name_en: <a href="https://www.cloopen.com/">Cloopen</a>
              company_logo: cloopen.png
              # company_url: https://www.cloopen.com/
              designation: 技术预研部实习生 Algorithm Intern
              description_zh: 人脸检测、活体检测（2018年7-8月）
              description_en: Worked on human face liveness detection and gesture recognition (Jul 2018 - Aug 2018)
              visibility: true

author_education_details:
              - college_logo: tbsi.png
                college_name_zh: <a href="https://www.tsinghua.edu.cn/">清华大学</a>, <a href="https://www.tbsi.edu.cn/"> 清华-伯克利深圳学院</a>
                college_name_en: <a href="https://www.tbsi.edu.cn/en/">Tsinghua-Berkeley Shenzhen Institute</a>, <a href="https://www.tsinghua.edu.cn/publish/thu2018en/index.html"> Tsinghua University </a>
                # college_url: https://www.tbsi.edu.cn/en/
                college_degree: 数据科学和信息技术 Data Science and Information Technology
                description: 工学硕士 Master of Science, 2018-2021 (Expected)
                visibility: true
              - college_logo: ecn.png
                college_name_zh: <a href="https://www.ec-nantes.fr/">南特中央理工 École Centrale de Nantes</a>
                # college_url: https://www.ec-nantes.fr/
                college_degree: 信号、控制与机器人方向交换生 Exchange Student of Signal, Control, and Robotics
                description: 基础硕士 Foundation Master, 2017-2018
                visibility: true
              - college_logo: tju.png
                college_name_zh: <a href="http://www.tju.edu.cn/">天津大学</a>, <a href="http://seea.tju.edu.cn/"> 电气自动化与信息工程学院 </a>
                college_name_en: <a href="http://seea.tju.edu.cn/english/">School of Electrical and Information Engineering</a>, <a href="http://www.tju.edu.cn/english/"> Tianjin University </a>
                # college_url: http://www.tju.edu.cn/english/
                college_degree: 自动化 Automation (Electrical and Electronic Engineering)
                description: 工学学士 Bachelor of Engineering, 2014-2018
                visibility: true

author_certificate_details:
              - certificate_logo: international_relations.jpg
                institute_name: Coursera, see <a href="https://www.coursera.org/account/accomplishments/verify/A49272V49X9T"> Certificate </a>  Coursera网络课程, 参见 <a href="https://www.coursera.org/account/accomplishments/verify/A49272V49X9T"> 证书 </a>
                # college_url: https://www.coursera.org/account/accomplishments/certificate/A49272V49X9T
                certificate_name: Understanding International Relations Theory
                description: Online Course, Jun 2019
                visibility: true
              - certificate_logo: political_economy.jpg
                institute_name: Coursera, see <a href="https://www.coursera.org/account/accomplishments/verify/H5Z8HJYM3BCZ"> Certificate </a>  Coursera网络课程, see <a href="https://www.coursera.org/account/accomplishments/verify/H5Z8HJYM3BCZ"> 证书 </a>
                # college_url: https://www.coursera.org/account/accomplishments/certificate/A49272V49X9T
                certificate_name: Political Economy of Institutions and Development
                description: Online Course, Dec 2019
                visibility: true

author_project_details:
              - project_thumbnail: wcloud.png
                project_title: Evaluating Online Public Sentiments towards China":" A Case Study of Twitter Discourse during the 2019 Chinese National Day
                project_description: （仅英文）收集并分析2019年10月1日前后与中国国庆有关的中英文推特数据，研究推特话语对华情感在时间、空间、用词等方面的特点。
                project_url: <a href="/social%20media%20&%20politics/2019/11/28/What-can-we-find-from-the-Chinese-National-Day-Twitter-data/"> 更多 Detail </a> | <a href="https://github.com/JaimeLaVie/National_Day_Public_Opinion_Mining"> Github </a>
                visibility: true

author_contact_information:
              - contact_image: contact_me.jpg
                email: E-mail  xyk18@mails.tsinghua.edu.cn
                tel: Tel  +86 15620079650
                visibility: true

# social links
twitter_username: XYekai
github_username:  JaimeLaVie
# facebook_username: 
linkedin_username: yekai-xu-b73596156/
# behance_username: 
# instagram_username: 
# medium_username: 
# telegram_username: 
# dribbble_username: 
# flickr_username: 

#for comments using disqus
# disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
wakatime_username: XU_Yekai

# formspree (contact form)
formspree_email: xyk18@mails.tsinghua.edu.cn

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_certificate_details: true
show_author_project_details: true
show_author_contact_information: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
